[project]
name = "federated-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.124.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0",
    "uvicorn[standard]>=0.38.0",
]
